apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: azure-firewall-updater
  namespace: azure-firewall-updater
  labels:
    app: azure-firewall-updater
spec:
  selector:
    matchLabels:
      app: azure-firewall-updater
  template:
    metadata:
      labels:
        app: azure-firewall-updater
    spec:
      containers:
        - name: azure-firewall-updater
          image: registry.digitalocean.com/luggage/azure-firewall-updater:9bd001e
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: azure-sp
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
          resources:
            requests:
              memory: "32Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
