name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 120

      - name: Get short SHA
        id: sha
        run: echo "sha7=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: make docker-publish TAG=${{ steps.sha.outputs.sha7 }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Get cluster
        run: doctl kubernetes cluster kubeconfig save discworld

      - name: Deploy to Kubernetes
        run: make deploy TAG=${{ steps.sha.outputs.sha7 }}

  notify-success:
    runs-on: ubuntu-latest
    needs: [build-and-publish]
    if: success()

    steps:
      - name: Notify on success
        run: curl -d "Azure Firewall Updater deployed ðŸ¥³" ntfy.sh/massivepixel_45h6jk

  notify-failure:
    needs: [build-and-publish]
    if: failure()
    runs-on: ubuntu-latest

    steps:
      - name: Notify on failure
        run: curl -d "Azure Firewall Updater failed to deploy ðŸ˜­" ntfy.sh/massivepixel_45h6jk
